Adicionando traducao da strings.xml para PT/BR - Add PT/BR translatio…
googlesamples/android-sunflower pull request #573
Opened 2020-01-31 13:43 UTC by mxrpxcx

…n to strings.xml

2020-03-06 13:22 UTC, gianei requested changes

2020-03-06 13:22 UTC, gianei commented on app/src/main/res/values/strings.xml
> +    <string name="available" translation_description="Text for the header of the plant list page indicating the available plants for users to choose from.">Plantas disponíveís</string>
There is a wrong additional accent. It should be `Plantas disponíveis`

2020-03-06 13:22 UTC, gianei commented on app/src/main/res/values/strings.xml
> +    <string name="add_plant" translation_description="Button text that prompts user to navigate to the Plant List to add plants to their empty garden.">Adicionar uma Plantat</string>
`Adicionar uma Planta`

2020-03-06 13:22 UTC, gianei commented on app/src/main/res/values/strings.xml
> +        <item quantity="one" translation_description="Suffix for the text describing how often a plant should be watered, singular. Used in combination with watering_needs_prefix: 'Watering needs: ev
`todo dia`

2024-08-02 10:31 UTC, riggaroo commented
Hi, 
Thanks for your contribution, however Sunflower is going to be archived in favour of maintaining a smaller set of up-to-date set of compose-samples, that can be found here: https://github.com/android/compose-samples, as well as snippets that can be found here: https://github.com/android/snippets.

Please feel free to keep your fork up-to-date for your learning, but this repository will be archived shortly.

2024-08-02 10:31 UTC, closed without merging